{% set name = "gwtools" %}
{% set version = "1.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7d807fe539103c3039ac9aa55c69ba0ef59d8de7683f3999b3d747a819fe62c9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pypandoc
    - python
    - setuptools
  run:
    - numpy
    - python
    - python-lal
    - python-lalsimulation
    - scipy

test:
  imports:
    - gwtools
    - gwtools.const
    - gwtools.gwtools
    - gwtools.gwutils
    - gwtools.harmonics
    - gwtools.mismatch
    - gwtools.rotations

about:
  home: "https://bitbucket.org/chadgalley/gwtools"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "A collection of gravitational wave tools"
  description: "A collection of useful functions and tools for working with gravitational waveform data."

extra:
  recipe-maintainers:
    - duncanmmacleod
    - sfield17
    - vijayvarma392
