{% set name = "gwtools" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7eb1dba1ebf8d56d3ff590fed7e0fd90d79f113ddef00f2320b2d032ca410e61

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - numpy
    - python >=3
    - python-lal
    - python-lalsimulation
    - scipy

test:
  requires:
    - pip
  imports:
    - gwtools
    - gwtools.const
    - gwtools.gwtools
    - gwtools.gwutils
    - gwtools.harmonics
    - gwtools.mismatch
    - gwtools.rotations
  commands:
    # check the metadata
    - python -m pip check gwtools
    - python -m pip show gwtools

about:
  home: https://bitbucket.org/chadgalley/gwtools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of gravitational wave tools
  description: A collection of useful functions and tools for working with gravitational waveform data.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - sfield17
    - vijayvarma392
