{% set name = "gwtools" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1344d4e084b2f2daf1365c1136f51e490ace7b1f228477da63abb5bfcaa87db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pypandoc
    - python >=3
    - setuptools
  run:
    - numpy
    - python >=3
    - python-lal
    - python-lalsimulation
    - scipy

test:
  imports:
    - gwtools
    - gwtools.const
    - gwtools.gwtools
    - gwtools.gwutils
    - gwtools.harmonics
    - gwtools.mismatch
    - gwtools.rotations

about:
  home: https://bitbucket.org/chadgalley/gwtools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of gravitational wave tools
  description: A collection of useful functions and tools for working with gravitational waveform data.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - sfield17
    - vijayvarma392
